server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.242.116:3306/car?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com.godric.cms.dao: trace

mybatis-plus:
  mapper-locations: classpath:/xml/*.xml
  type-aliases-package: com.godric.cms.common.po.*
  configuration:
    map-underscore-to-camel-case: true

# 配置项目的时候需要进行修改
file:
  uploadFolder: F:\\workspace_j\\library\\car\\car-manage-system\\src\\main\\resources\\static\\upload\\